In [7]:
import pandas as pd
ml100k_id_2_netflix_vector = pd.read_pickle("ml100k_id_2_netflix_vector.pkl")

In [8]:
matched_pairs = pd.read_pickle("matched_pairs_new.pkl")

In [9]:
for p in matched_pairs:
    if p[1]['film_id'] == 16552:
        print(p)

[{'filmname_given': 'GoldenEye (1995)', 'film_id': 2, 'title': 'GoldenEye', 'year': 1995, 'cast': ['Pierce Brosnan', 'Sean Bean', 'Izabella Scorupco', 'Famke Janssen', 'Joe Don Baker', 'Judi Dench', 'Robbie Coltrane', 'Tchéky Karyo', 'Gottfried John', 'Alan Cumming', 'Desmond Llewelyn', 'Samantha Bond', 'Michael Kitchen', 'Serena Gordon', 'Simon Kunz', 'Pavel Douglas', 'Olivier Lajous', 'Billy J. Mitchell', 'Constantine Gregory', 'Minnie Driver', 'Michelle Arthur', 'Ravil Isyanov', 'Vladimir Milanovich', 'Trevor Byfield', 'Peter Majer', 'Paul Bannon', 'Simone Bechtel', 'Martin Campbell', 'Mark Chapman', 'Kenneth Coombs', 'Simon Crane', 'Terrance Denville', 'Ian Durrant', 'Max Faulkner', 'Juliet Forester', 'Stefan Kopiecki', 'Jo Anna Lee', 'Derek Lyons', 'Wayne Michaels', 'Bhasker Patel', 'Paul Sacks', 'Michael G. Wilson'], 'genres': ['Action', 'Adventure', 'Thriller'], 'director': ['Martin Campbell'], 'plot': ['Years after a friend and fellow 00 agent is killed on a joint mission, a se

IndexError: list index out of range

In [10]:
ml100k_id_2_meta_info = {}
for p in matched_pairs:
    if len(p) >= 2:
        ml100k_id_2_meta_info[p[1]['film_id']] = p[1]
        

In [11]:
ml100k_id_2_meta_info[16552]

{'filmname_given': 'GoldenEye(1995)',
 'film_id': 16552,
 'title': 'GoldenEye',
 'year': 1995,
 'cast': ['Pierce Brosnan',
  'Sean Bean',
  'Izabella Scorupco',
  'Famke Janssen',
  'Joe Don Baker',
  'Judi Dench',
  'Robbie Coltrane',
  'Tchéky Karyo',
  'Gottfried John',
  'Alan Cumming',
  'Desmond Llewelyn',
  'Samantha Bond',
  'Michael Kitchen',
  'Serena Gordon',
  'Simon Kunz',
  'Pavel Douglas',
  'Olivier Lajous',
  'Billy J. Mitchell',
  'Constantine Gregory',
  'Minnie Driver',
  'Michelle Arthur',
  'Ravil Isyanov',
  'Vladimir Milanovich',
  'Trevor Byfield',
  'Peter Majer',
  'Paul Bannon',
  'Simone Bechtel',
  'Martin Campbell',
  'Mark Chapman',
  'Kenneth Coombs',
  'Simon Crane',
  'Terrance Denville',
  'Ian Durrant',
  'Max Faulkner',
  'Juliet Forester',
  'Stefan Kopiecki',
  'Jo Anna Lee',
  'Derek Lyons',
  'Wayne Michaels',
  'Bhasker Patel',
  'Paul Sacks',
  'Michael G. Wilson'],
 'genres': ['Action', 'Adventure', 'Thriller'],
 'director': ['Martin Campbel

In [5]:
from collections import Counter
all_genres_counter = Counter()
all_genres = set()
for k in ml100k_id_2_meta_info:
    all_genres.update(ml100k_id_2_meta_info[k]['genres'])
    all_genres_counter.update(ml100k_id_2_meta_info[k]['genres'])

In [6]:
#use all genres
len(all_genres)

26

In [7]:
all_genres_counter

Counter({'Animation': 41,
         'Adventure': 185,
         'Comedy': 519,
         'Family': 132,
         'Fantasy': 127,
         'Action': 227,
         'Thriller': 328,
         'Crime': 265,
         'Drama': 742,
         'Mystery': 131,
         'History': 49,
         'Romance': 364,
         'Talk-Show': 20,
         'Music': 44,
         'Musical': 48,
         'Biography': 73,
         'War': 53,
         'Documentary': 35,
         'Sci-Fi': 98,
         'Sport': 36,
         'Western': 30,
         'Short': 11,
         'Horror': 78,
         'Reality-TV': 3,
         'Film-Noir': 10,
         'Game-Show': 1})

In [31]:
all_directors = set()
all_directors_counter = Counter()
for k in ml100k_id_2_meta_info:
    all_directors.update(ml100k_id_2_meta_info[k]['director'])
    all_directors_counter.update(ml100k_id_2_meta_info[k]['director'])

In [22]:
all_directors_counter

Counter({'John Lasseter': 1,
         'Martin Campbell': 2,
         'Allison Anders': 3,
         'Alexandre Rockwell': 1,
         'Robert Rodriguez': 2,
         'Barry Sonnenfeld': 5,
         'Jon Amiel': 2,
         'Yimou Zhang': 2,
         'Chris Noonan': 1,
         'David Fincher': 2,
         'Bryan Singer': 2,
         'Woody Allen': 9,
         'Don DuPree': 8,
         'Stephen Herek': 1,
         'Josiane Balasko': 1,
         'Marleen Gorris': 2,
         'Philip Haas': 1,
         'Brian Henson': 1,
         'David Lane': 1,
         'Mel Gibson': 2,
         'Martin Scorsese': 3,
         'Stanley Tong': 4,
         'Mike Nichols': 4,
         'Edward Burns': 2,
         'Michael Bay': 1,
         'Ron Howard': 3,
         'Joel Schumacher': 4,
         'Luis Buñuel': 1,
         'Tony Scott': 5,
         'Terry Zwigoff': 1,
         'Gregg Araki': 1,
         'Dwight H. Little': 3,
         'Antonia Bird': 2,
         'Irwin Winkler': 1,
         'Kathryn Bigelow': 

In [23]:
len(all_directors_counter)

863

In [26]:
len(set(k for k in all_directors_counter if all_directors_counter[k] > 1))

278

In [27]:
#directors count >1
filtered_directors = set(k for k in all_directors_counter if all_directors_counter[k] > 1)

In [28]:
len(filtered_directors)

278

In [30]:
all_cast = set()
all_cast_counter = Counter()
for k in ml100k_id_2_meta_info:
    all_cast.update(ml100k_id_2_meta_info[k]['cast'])
    all_cast_counter.update(ml100k_id_2_meta_info[k]['cast'])

In [33]:
len(all_cast_counter)

42317

In [38]:
len(set(k for k in all_cast_counter if all_cast_counter[k] > 5))

1053

In [39]:
#cast count >5 
filtered_cast = set(k for k in all_cast_counter if all_cast_counter[k] > 5)

## Basic Desctription2Vec Model

In [118]:
#pd.to_pickle({"cast_used": list(filtered_cast), "directors_used": list(filtered_directors), "geners_used": list(all_genres)}, "ordered_lists_for_desc2vec.pkl")

In [12]:
selected_features = pd.read_pickle("ordered_lists_for_desc2vec.pkl")

In [13]:
filtered_cast = selected_features["cast_used"]
filtered_directors = selected_features["directors_used"]
all_genres = selected_features["geners_used"]

In [14]:
len(filtered_cast)

1053

In [15]:
ml100kid_2_plot_vector = pd.read_pickle("ml100kid_2_plot_vector.pkl")

In [26]:
import numpy as np

In [32]:
def filminfo2features(f_id,film_info):
#    cast_block = [0] * len(filtered_cast)
    cast_block = []
#    directors_block = [0] * len(filtered_directors)
    directors_block = []
    genres_block = [0] * len(all_genres)
#     for c in film_info['cast']:
#         if c in filtered_cast:
#             cast_block[filtered_cast.index(c)] = 1
#     for d in film_info['director']:
#         if d in filtered_directors:
#             directors_block[filtered_directors.index(d)] = 1
    for g in film_info['genres']:
        if g in all_genres:
            genres_block[all_genres.index(g)] = 1
            
    
    features = cast_block + directors_block + genres_block + list(ml100kid_2_plot_vector[f_id])
    for ind, f in enumerate(features):
        if f == np.nan or f == np.inf or str(f) == "nan":
            features[ind] = 0
    return features

In [33]:
filminfo2features(16552, ml100k_id_2_meta_info[16552])

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0.03619384765625,
 0.013042449951171875,
 0.0228271484375,
 -0.0022735595703125,
 -0.052490234375,
 -0.028167724609375,
 -0.00592041015625,
 -0.044952392578125,
 0.12567138671875,
 0.087646484375,
 0.0133056640625,
 -0.13885498046875,
 -0.00152587890625,
 0.07275390625,
 -0.1671142578125,
 0.04248046875,
 0.04730224609375,
 0.091064453125,
 0.01251220703125,
 -0.0125732421875,
 0.06557750701904297,
 0.020599365234375,
 0.0350341796875,
 0.010986328125,
 -0.0635223388671875,
 -0.1171875,
 -0.003536224365234375,
 0.2579345703125,
 -0.03179931640625,
 0.022552490234375,
 0.043212890625,
 -0.0111083984375,
 0.06805419921875,
 -0.088623046875,
 -0.0182647705078125,
 0.048828125,
 -0.044525146484375,
 -0.0358734130859375,
 0.1378173828125,
 0.0230865478515625,
 0.08465576171875,
 -0.02056884765625,
 0.053462982177734375,
 -0.0204620361328125,
 -0.0546875,
 -0.03271484375,
 0.0430603027343

In [34]:
X = []
y = []

for i in ml100k_id_2_meta_info:
    if str(i) in ml100k_id_2_netflix_vector:
        X.append(filminfo2features(int(i),ml100k_id_2_meta_info[i]))
        y.append(ml100k_id_2_netflix_vector[str(i)])


In [29]:
print(len(X))
print(len(y))
print(len(X[0]))
print(len(y[0]))

1309
1309
326
100


In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [36]:
from sklearn.neural_network import MLPRegressor

reg = MLPRegressor(max_iter =50000, hidden_layer_sizes = (1000, 500, 200), random_state = 42, learning_rate_init = 0.001, verbose = True, early_stopping = True, tol=0.1).fit(X_train, y_train)

reg.score(X_train, y_train)

Iteration 1, loss = 3.35762781
Validation score: -0.015396
Iteration 2, loss = 3.31407903
Validation score: -0.010823
Iteration 3, loss = 3.29216117
Validation score: -0.009443
Iteration 4, loss = 3.27773347
Validation score: -0.010544
Iteration 5, loss = 3.26401808
Validation score: -0.009622
Iteration 6, loss = 3.24755773
Validation score: -0.010128
Iteration 7, loss = 3.22843477
Validation score: -0.011058
Iteration 8, loss = 3.20530537
Validation score: -0.011497
Iteration 9, loss = 3.18054732
Validation score: -0.013482
Iteration 10, loss = 3.15023296
Validation score: -0.014432
Iteration 11, loss = 3.11338111
Validation score: -0.016952
Iteration 12, loss = 3.07627129
Validation score: -0.023807
Validation score did not improve more than tol=0.100000 for 10 consecutive epochs. Stopping.


0.005126029568968019

In [45]:
#BEST RES
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.decomposition import PCA

reg = RandomForestRegressor(max_samples = 0.8, n_estimators = 100, random_state = 32, max_depth = 500, max_features = 0.9, n_jobs = -1, verbose = True)

estimators = [('reduce_dim', PCA(n_components = 300)), ('clf', reg)]
pipe = Pipeline(estimators)

pipe.fit(X_train, y_train)

pipe.score(X_train, y_train)


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   25.0s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.1min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


0.5182642490893188

In [224]:
reg = MLPRegressor(max_iter =50000, batch_size = 2, hidden_layer_sizes = (500), random_state = 42, learning_rate_init = 0.00001, verbose = True, early_stopping = True, tol=0.00000001)

estimators = [('reduce_dim', PCA(n_components = 300)), ('clf', reg)]
pipe = Pipeline(estimators)

pipe.fit(X_train, y_train)

pipe.score(X_train, y_train)

Iteration 1, loss = 3.36931376
Validation score: -0.031549
Iteration 2, loss = 3.36310646
Validation score: -0.030032
Iteration 3, loss = 3.35721957
Validation score: -0.028630
Iteration 4, loss = 3.35165806
Validation score: -0.027312
Iteration 5, loss = 3.34637024
Validation score: -0.026059
Iteration 6, loss = 3.34134251
Validation score: -0.024887
Iteration 7, loss = 3.33654543
Validation score: -0.023782
Iteration 8, loss = 3.33198530
Validation score: -0.022736
Iteration 9, loss = 3.32763110
Validation score: -0.021758
Iteration 10, loss = 3.32345628
Validation score: -0.020825
Iteration 11, loss = 3.31944806
Validation score: -0.019950
Iteration 12, loss = 3.31561086
Validation score: -0.019113
Iteration 13, loss = 3.31195024
Validation score: -0.018318
Iteration 14, loss = 3.30845154
Validation score: -0.017593
Iteration 15, loss = 3.30509962
Validation score: -0.016902
Iteration 16, loss = 3.30190894
Validation score: -0.016252
Iteration 17, loss = 3.29885468
Validation score:

0.01274407179670694

In [225]:
pipe.score(X_test, y_test)

-0.005974502326286649

In [117]:
y_train[3]

array([ 0.93006957, -1.2708417 ,  3.820607  ,  6.519576  , -1.2214589 ,
        3.9977937 ,  3.562634  ,  1.5995691 ,  0.45073134, -1.6945956 ,
        4.070808  , -0.6472699 ,  1.2470887 ,  2.3091385 , -0.45052874,
        0.32903165,  3.2048037 , -1.6029013 , -1.1842073 ,  0.29911363,
        0.25302085,  3.3926702 , -4.4643073 , -7.4735627 , -0.2535935 ,
        3.8819363 , -2.7396963 , -1.5637867 , -7.300224  , -1.2753513 ,
        1.9378732 , -1.7383015 , -0.93467706, -4.2146854 , -1.208196  ,
       -3.437232  ,  1.0285127 ,  1.3437836 , -4.3510747 , -5.2113175 ,
       -5.264692  , -2.0488696 , -2.5054877 ,  5.414327  , -1.1867591 ,
       -0.29509985,  2.033888  ,  2.5774252 , -2.775059  , -1.7141255 ,
       -3.8739405 , -0.94326586, -1.1076707 ,  1.8872408 ,  1.2827433 ,
       -1.8268166 ,  6.4600196 ,  1.1052852 ,  3.470289  , -1.2091595 ,
       -0.5826379 ,  2.034031  , -2.864609  , -7.1188917 , -0.407277  ,
       -1.3047825 , -3.1543705 ,  1.3963555 , -0.6484949 ,  0.77

In [46]:
import numpy as np
def mean_absolute_percentage_error(y_true, y_pred): 
    #y_true, y_pred = check_arrays(y_true, y_pred)

    ## Note: does not handle mix 1d representation
    #if _is_1d(y_true): 
    #    y_true, y_pred = _check_1d_array(y_true, y_pred)

    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mean_absolute_percentage_error(pipe.predict(X_train), y_train)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


1611.0674120389344

In [47]:
mean_absolute_percentage_error(pipe.predict(X_test), y_test)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


2190.2768248055518

In [80]:
len(X_train[0])

1357

In [179]:
pipe.predict(X_test)[0]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 200 out of 200 | elapsed:    0.1s finished


array([-0.46026051,  0.19402807, -0.04265283,  1.73502329, -1.5306652 ,
       -0.26659754,  0.48626567,  1.00753443, -0.30449739,  0.67664642,
       -0.54391193,  1.01407655,  0.28592961,  1.31553625, -1.51800012,
       -0.82256561,  1.13815913,  0.59191285,  1.23882406,  0.74256957,
        0.08418256,  0.21547546, -0.14444786, -1.12139357, -0.3522443 ,
        0.66474539, -0.22223806, -0.49783863,  0.49491934, -0.61010158,
       -0.59053456, -0.31218332,  0.85014732,  0.15308276, -1.20703037,
       -0.47021922, -0.90309288, -0.74526619, -0.77101818, -0.88929391,
       -0.68242629,  0.15019169, -0.31965147,  0.05194919,  1.12099409,
        0.74765599,  0.52988931,  1.21592131,  0.46862806, -0.94794762,
       -0.31159936, -1.34034299, -0.36912042,  0.1911385 ,  0.66635378,
       -1.0289663 ,  0.05353255,  0.07891809,  0.6107973 , -1.07064737,
        0.52535393,  0.11898236,  0.31962901,  1.08107451, -1.41030463,
        0.32139318, -0.03505894,  0.69151983, -0.50702772, -0.83

In [180]:
y_test[0]

array([-0.94805306, -0.86054283, -2.3617432 , -2.8747718 , -2.3547456 ,
        0.92173856, -2.6018674 , -1.5730035 , -2.2251623 , -1.391424  ,
        0.65895855,  4.358042  ,  1.0239263 , -0.7620412 , -0.53967327,
       -2.140008  ,  0.836519  ,  2.0497894 , -0.09867645,  2.6093538 ,
        0.8456746 , -0.42942286,  1.3889185 ,  6.770804  , -2.944916  ,
       -0.43319607, -3.3078191 ,  1.5132325 , -2.218396  , -0.5730735 ,
       -0.5580824 ,  1.2542199 ,  0.81829995,  0.98145264,  0.39524373,
       -0.47316527, -0.49425668, -0.64041483, -1.1474727 , -1.1557547 ,
        2.495936  , -1.0510818 ,  3.4660695 , -1.8382903 , -2.9717503 ,
        0.12379408,  3.8247912 ,  0.15860595,  3.0268824 , -3.4290454 ,
       -1.863509  , -2.2796316 , -0.42671666, -0.772677  ,  0.4996287 ,
       -6.7019515 ,  0.2652769 , -0.3545774 ,  0.37202424,  0.51008475,
        3.6856086 , -1.3296894 ,  2.0681522 ,  0.72010314, -0.7618087 ,
        4.350698  , -0.76480687, -0.4838566 ,  3.1737845 , -3.31

## Doc2Vec

In [278]:
import nltk
tokenizer = nltk.RegexpTokenizer(r"\w+")

tokenizer.tokenize("dfsdfsd!! dfdsf 3: ff")

['dfsdfsd', 'dfdsf', '3', 'ff']

In [275]:
from nltk.corpus import stopwords
eng_stopwords = stopwords.words('english')

In [295]:
from nltk.stem import WordNetLemmatizer, PorterStemmer
nltk.download()

lemmatizer = WordNetLemmatizer() 
stemmer = PorterStemmer()
  
# a denotes adjective in "pos" 
print("better :", lemmatizer.lemmatize("better", pos ="a")) 

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
better : good


In [296]:
stemmer.stem("playing")

'play'

# For every plot remove punctuation, remove stopwords, do lowercase, lemmatizing, take unique words

In [310]:
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
  
print("rocks :", lemmatizer.lemmatize("rocks")) 
print("corpora :", lemmatizer.lemmatize("corpora")) 
  
# a denotes adjective in "pos" 
print("better :", lemmatizer.lemmatize("better", pos ="a")) 

rocks : rock
corpora : corpus
better : good


In [311]:
plot_corpus = []
for k in ml100k_id_2_meta_info:
    plot_corpus.append(list(set([lemmatizer.lemmatize(x) for x in list(filter(lambda tok: tok not in eng_stopwords ,tokenizer.tokenize(" ".join(ml100k_id_2_meta_info[k]['plot']).lower())))])))

In [312]:
plot_corpus[0]

['jealous',
 'treasure',
 'realize',
 'jwelch5742',
 'run',
 'com',
 'come',
 'home',
 'marcos',
 'outside',
 'xtnb64a',
 'especially',
 'worse',
 'playing',
 'move',
 'ranger',
 'known',
 'believe',
 'lost',
 'go',
 'arrives',
 'figure',
 'clock',
 'jealousy',
 'young',
 'chisholm',
 'position',
 'return',
 'must',
 'kenneth',
 'arrogant',
 'davis',
 'party',
 'phillips',
 'think',
 'pas',
 'become',
 'planet',
 'family',
 'quickly',
 'escape',
 'buy',
 'try',
 'back',
 'acosta',
 'hearted',
 'becomes',
 'action',
 'importantly',
 'andy',
 'separated',
 'watched',
 'story',
 'secret',
 'like',
 'delay',
 'rid',
 'around',
 'mother',
 'good',
 'moving',
 'andys',
 'real',
 'neighbor',
 'journey',
 'people',
 'eduardo',
 'clutch',
 'mobile',
 'birthday',
 'hots',
 'lightyear',
 'two',
 'doll',
 'sid',
 'instantly',
 'cowboy',
 'toy',
 'jeopardized',
 'spaceman',
 'favorite',
 'kind',
 'top',
 'buzz',
 'take',
 'wiggins',
 'rampant',
 'window',
 'ruthless',
 'worry',
 'fall',
 'find',
 '

In [313]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?' ]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [321]:
X[0].toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [ ]:
import gensim.downloader as api
pretrained_word_vects = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
print(pretrained_word_vects.most_similar(positive=['car', 'minivan'], topn=5))

In [ ]:
try:
    vec_cameroon = wv['cameroon']
except KeyError:
    print("The word 'cameroon' does not appear in this model")

In [ ]:
## Take words from sentence with tfidf > XXXXX , take top 5 vectors by tfidf (if not exist, ) vectors pretrained on google news corresponding to these words (if exists) and average them. 